module.exports = {
    BillService: require('./bill.service'),
    CategoryService: require('./category.service'),
    CartService: require('./cart.service'),
    MenuService: require('./menu.service'),
    OrderService: require('./order.service'),
    OrderDetailService: require('./order-detail.service'),
    PaymentService: require('./payment.service'),
    QrCodeService: require('./qrcode.service'),
    TableService: require('./table.service'),
    TableStatusService: require('./table-status.service'),
    UserService: require('./user.service'),
    UserRoleService: require('./user-role.service'),
    StoreService: require('./store.service'),
};
